apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-test-deployment
  labels: 
    app: Deployment-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-pod
  template:
    metadata:
      labels:
        app: deployment-pod
    spec:
      containers:
      - name: secret-deployment-container
        image: nginx:latest
        ports:
        - containerPort: 80
        # envFrom:
        #  - secretRef:
        #     name: test-secrets
        volumeMounts:
          - name: config-mount-volume
            mountPath: /app/config
            readOnly: true
      volumes:
        - name: config-mount-volume ## volumemounts.name and volumes.name should be the same.
          secret:
            secretName: test-secrets
        
